server:
  port: 9909
spring:
  application:
    name: user
  #  cloud:
  #    # nacos 配置
  #    nacos:
  #      discovery:
  #        server-addr: localhost:8848

  redis:
    host: 192.168.3.111
    port: 6379
    password: n1yEl39pMQZkH
    database: 13

  # 配置连接数据库
  datasource:
    name: tvpanda
    url: jdbc:mysql://192.168.3.111:3306/seat-account?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 配置使用druid数据源 数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #2.连接池配置
    #初始化连接池的连接数量 大小，最小，最大
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  # seata 配置分布式事务
#  seata:
#    enabled: true
#    enable-auto-data-source-proxy: true
#    tx-service-group: my_test_tx_group # 与nacos注册的分组一致(注意seata配置文件)
# RocketMq

rocketmq:
  name-server: 192.168.3.111:9876 # 访问地址
  producer:
    group: Pro_Group # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2


