# 配置redis信息
redis:
  host: localhost #redis本地URL
  port: 6397  #redis端口(port)
  database: 8 #选择存储的数据库(0-15)
  pool:
    max-wait: 30000 #连接池最大阻塞等待时间(使用负值表示没有限制)
    max-active: 100 #连接池最大连接数(使用负值表示没有限制)
    max-idle: 20 #连接池中的最大空闲连接
    min-idle: 0 #连接池中的最小空闲连接
  timeout: 3000 #连接超时