server:
  port: 8086
#mongodb配置
spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:123456@localhost:27017/mongodemo
#      database: mongodemo
#      username: mongoadmin
#      password: 123456
#      host: localhost
#      port: 27017